export const FETCH_COUNTRIES = "FETCH_COUNTRIES";
export const FETCH_COUNTRIES_SUCCESS = "FETCH_COUNTRIES_SUCCESS";
export const FETCH_COUNTRIES_FAIL = "FETCH_COUNTRIES_FAIL";

export const FETCH_INTERNET_USAGE_PER_COUNTRY =
  "FETCH_INTERNET_USAGE_PER_COUNTRY";
export const FETCH_INTERNET_USAGE_PER_COUNTRY_SUCCESS =
  "FETCH_INTERNET_USAGE_PER_COUNTRY_SUCCESS";
export const FETCH_INTERNET_USAGE_PER_COUNTRY_FAIL =
  "FETCH_INTERNET_USAGE_PER_COUNTRY_FAIL";

export const FETCH_INTERNET_USAGE_PER_COUNTRY_AND_YEAR =
  "FETCH_INTERNET_USAGE_PER_COUNTRY_AND_YEAR";
export const FETCH_INTERNET_USAGE_PER_COUNTRY_AND_YEAR_SUCCESS =
  "FETCH_INTERNET_USAGE_PER_COUNTRY_AND_YEAR_SUCCESS";
export const FETCH_INTERNET_USAGE_PER_COUNTRY_AND_YEAR_FAIL =
  "FETCH_INTERNET_USAGE_PER_COUNTRY_AND_YEAR_FAIL";

export const FETCH_INTERNET_USAGE_PER_YEAR_BY_COUNTRY =
  "FETCH_INTERNET_USAGE_PER_YEAR_BY_COUNTRY";
export const FETCH_INTERNET_USAGE_PER_YEAR_BY_COUNTRY_SUCCESS =
  "FETCH_INTERNET_USAGE_PER_YEAR_BY_COUNTRY_SUCCESS";
export const FETCH_INTERNET_USAGE_PER_YEAR_BY_COUNTRY_FAIL =
  "FETCH_INTERNET_USAGE_PER_YEAR_BY_COUNTRY_FAIL";

export const FETCH_INTERNET_USAGE_IN_YEAR = "FETCH_INTERNET_USAGE_IN_YEAR";
export const FETCH_INTERNET_USAGE_IN_YEAR_SUCCESS =
  "FETCH_INTERNET_USAGE_IN_YEAR_SUCCESS";
export const FETCH_INTERNET_USAGE_IN_YEAR_FAIL =
  "FETCH_INTERNET_USAGE_IN_YEAR_FAIL";

